# simulate the firm value
V0 <- 100; mu <- 0.1; sigma <- 0.2
dt <- 1 / 252; Time <- 1
M <- Time / dt
n <- 10000
set.seed(117)
val <- rnorm(n*M,
   mean = (mu - sigma^2 / 2) * dt, 
   sd   = sigma * dt^0.5)

dlnV <- matrix(val, M, n)

V <- V0 * exp(apply(dlnV, 2, cumsum))

matplot(x = seq(0 + dt, Time, dt), y = V[, 1:5], type = 's', lty = 1, xlab = 'Time',
    ylab = 'Firm value trajectories',
    main = 'Trajectories of firm values in the Merton model')
# r risk-free interest rate and face value of the debt (K)
r <- 0.05; K <- 80
D <- exp(-r * Time) * mean((pmin(V[M, ], K)))
D # risky debt


# simulation of the Cox-Ingersoll-Ross (CIR) process
library(sde)
Time <- 1; dt <- 1/252; M <- Time / dt
lambda <- sde.sim(X0 = 0.1, delta = dt,T = Time, N = M, 
                     theta = c (0.05, 0.5, 0.2), model = "CIR")
n <- 5
set.seed(117); val <- rpois(n * (M + 1), lambda)
dN <- matrix(val, M + 1, n)
N <- apply(dN, 2, cumsum)

matplot(x = seq(0, Time, dt), y = N[, 1:5], type = 's', xlab = 'Time',
    ylab = "'Number of defaults' process trajectories",
    main = 'Trajectories of Cox processes ')


# Correlated defaults - the portfolio approach
library(copula)
# opula class with an 0.7 correlation
norm.cop <- normalCopula(0.7)
# 500 realizations of two uniformly distributed random variables with the Gaussian copula dependency
set.seed(117); u1 <- rCopula(500, norm.cop)
t.cop <- tCopula(0.7, df = 4)
set.seed(117); u2 <- rCopula(500, t.cop)

par(mfcol = c(1, 2))
plot(u1, main = 'Scatter graphs of random variable pairs generated by Gaussian copula')
plot(u2, main = 'Scatter graphs of random variable pairs generated by t-copula')

fit.ml <- fitCopula(norm.cop, u1, method = "ml")
fit.ml



